// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwfUMuLFiSUTqxHtBzGYtW6OZDpfdtRqQ',
    appId: '1:551805913731:web:4a1c0dde8da52e5ed9e9b6',
    messagingSenderId: '551805913731',
    projectId: 'pdv-f87d8',
    authDomain: 'pdv-f87d8.firebaseapp.com',
    storageBucket: 'pdv-f87d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvnpQvr3Xmqv10LKz3sfDc53X3_afLLp8',
    appId: '1:551805913731:android:08bd6967130e87d6d9e9b6',
    messagingSenderId: '551805913731',
    projectId: 'pdv-f87d8',
    storageBucket: 'pdv-f87d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGQuk3qKRG78w5pJYlPxMImbP6HcxDtrw',
    appId: '1:551805913731:ios:4e7a43a2139db94ad9e9b6',
    messagingSenderId: '551805913731',
    projectId: 'pdv-f87d8',
    storageBucket: 'pdv-f87d8.appspot.com',
    iosClientId: '551805913731-cpu0390kqk5poar6p8tnd5f9qf6vc3jv.apps.googleusercontent.com',
    iosBundleId: 'br.com.CodeGearDeveloper.gestaoPedidos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGQuk3qKRG78w5pJYlPxMImbP6HcxDtrw',
    appId: '1:551805913731:ios:4e7a43a2139db94ad9e9b6',
    messagingSenderId: '551805913731',
    projectId: 'pdv-f87d8',
    storageBucket: 'pdv-f87d8.appspot.com',
    iosClientId: '551805913731-cpu0390kqk5poar6p8tnd5f9qf6vc3jv.apps.googleusercontent.com',
    iosBundleId: 'br.com.CodeGearDeveloper.gestaoPedidos',
  );
}
